# Generated by Django 2.1.1 on 2018-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.IntegerField(null=True)),
                ('disiplinaOfertada', models.IntegerField(null=True)),
            ],
        ),
    ]
